server.port: 8111
thread:
  config:
    corePoolSize: 4
    maxPoolSize: 10000
    maxIdle: 8
entity.package: ${project.groupId}.${project.artifactId}.entity.db.
repository.package: ${project.groupId}.${project.artifactId}.repository.db.

spring:
  datasource:
    hikari:
      #最小空闲连接数量
      minimum-idle: 1
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: DatebookHikariCP
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
spring.jpa.database: mysql
spring.jpa.open-in-view: true
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.jdbc.time_zone: GMT+8
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.jpa.hibernate.naming.physical-strategy: com.ahaxt.competition.config.JpaNamingStrategy
spring.datasource.url: jdbc:mysql://localhost:3306/cms?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username: guest
spring.datasource.password: 123456


########################## Swagger ##########################
swagger.enable: true
swagger.url: Swagger:http://localhost:${server.port}/swagger-ui.html
swagger.basePackage: ${project.groupId}.${project.artifactId}.controller
swagger.title: Api\u6587\u6863 by ${project.name}
swagger.version: ${project.version}
swagger.description: ${project.description}
########################## redis ##########################
spring.redis.host: 127.0.0.1
spring.redis.port: 6379
#spring.redis.password: Demo-2017
spring.redis.jedis.pool.max-active: ${thread.config.maxPoolSize}
spring.redis.jedis.pool.max-wait: -1s
spring.redis.jedis.pool.max-idle: ${thread.config.maxIdle}
spring.redis.jedis.pool.min-idle: ${thread.config.corePoolSize}
spring.redis.timeout: 1000ms
spring.data.redis.repositories.enabled: false
########################## minio ##########################
minio:
  # minio通信地址
  endpoint: http://localhost:9000
  # minio登录用户名
  userName: minioadmin
  # minio登录密码
  password: minioadmin
  # 项目固定的bucketName
  bucketName: cms

